title: Jazzy jumpers
hero_image: images/banner.png
description: Create a memory game involving jazzy jumpers
theme: violet # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-12-01
steps: 
- title: Introduction
- title: What you will need
- title: Parts of the jumper
- title: New jumper
- title: Hide the jumper
- title: "What was on the jumper?"
- title: Recreate the jumper
- title: The right jumper
- title: "Challenge: enhance the game"